services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: emna_crm
      POSTGRES_USER: emna
      POSTGRES_PASSWORD: emna_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DJANGO_SECRET_KEY: "change-me"
      DJANGO_DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "*"
      DATABASE_URL: "postgres://emna:emna_pass@db:5432/emna_crm"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - media:/app/media

volumes:
  pgdata:
  media:
